# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm audit fix
    npm run build
  displayName: 'npm install, audit fix, and build'

- script: |
    npm run test -- --testPathPattern=src/test/Registertest.js --watchAll=false --coverage
  displayName: 'Run React unit tests'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build' 
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/coverage/lcov.info'
    testRunTitle: 'React Unit Tests'
  displayName: 'Publish test results'
