# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm audit fix
    npm run build
  displayName: 'npm install, audit fix, and build'

- script: |
    npm install mocha chai --save-dev
    npx mocha src/test/Registertest.js --reporter mocha-junit-reporter --reporter-options mochaFile=results/test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'results/test-results.xml'
    testRunTitle: 'Registertest Results'
  displayName: 'Publish test results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build' 
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'
